spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/sub1?characterEncoding=UTF-8
    username: root
    password: Rmaqkswl1!

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

firebase:
  config:
    path: "C:/Users/multicampus/source/pjt-auth-97ed8-firebase-adminsdk-bniyn-80f0af0f6d.json"
    path2: "write your firebase-adminsdk-json to path"